### ISSUE TITLE
와 뭔가해서봤는데

### ISSUE THREAD

**Issue by wo7864** [altmshfkgudtjr/ELEposition#1]
기능은 당연한건데 디자인 졸라 있어보이게 만들었네 형석아 어케했노,,

**Comment by altmshfkgudtjr** [comment]
> 기능은 당연한건데 디자인 졸라 있어보이게 만들었네 형석아 어케했노,,

[기능은 당연한건데](https://github.com/altmshfkgudtjr/ELEposition/issues/1) ㅋㅋㅋㅋㅋㅋㅋㅋㅋ이 말 개웃기노ㅋㅋ
Mac OS Big Sur 처럼 한 번 만들어보고싶었음 ㅋㅋ
